### ISSUE TITLE
Sunday never triggers

### ISSUE THREAD

**Issue by pascalStm** [paragi/chronos#2]
Using the parameter "\* \* w1,7 1 0" e-chron has never triggers the dimache 1:00.
the problem comes from the line code 523 "nt [10] = ((Date.getDay () + 7) 8% + 1);" is replaced by fear "nt [10] = (Date.getDay () Date.getDay (?): 7);"

**Comment by paragi** [comment]
Thank you for your contribution to improve the module!

I will look into it, soon, and let you know how when its fixed.

Please note that week day 1 = Monday. Your code will change it to 1 = 
Sunday.

Best regards
Simon Rigét

Den 13-11-2015 kl. 14:47 skrev pascalStm:

> Using the parameter "\* \* w1,7 1 0" e-chron has never triggers the 
> dimache 1:00.
> the problem comes from the line code 523 "nt [10] = ((Date.getDay () + 
> 7) 8% + 1);" is replaced by fear "nt [10] = (Date.getDay () 
> Date.getDay (?): 7);"
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/paragi/chronos/issues/2.

## 

Simon Rigét
Kløvermarksvej 17
Annisse
3200 Helsinge
Tlf. 4096 8217

**Comment by pascalStm** [comment]
The getDay() method returns the day of the week (from 0 to 6) for the specified date.
Note: Sunday is 0, Monday is 1, and so on.
And chronos the Day of week from 1 to 7, Sunday is 7
Best regards

**Comment by paragi** [comment]
Hi pascalStm

I can not recreate the issue.

could you please run this code:

var chronos = require('e-chron');
console.log(chronos.nextTime("\* \* w1,7 1 0",false,1447400000));

This is the function that calculates the next execution time.
The last parameter is the current time, corresponding to Fri Nov 13 
07:33:20 UTC 2015

It should return this value, if you are in the CET time zone (UTC-1):

{ time: '1447545600.000', error: '' }

Corresponding to: Sun Nov 15 00:00:00 UTC 2015

What time zone are you in?

Can you give me a code example that failes?

Best regards
Simon

Den 14-11-2015 kl. 15:20 skrev pascalStm:

> The getDay() method returns the day of the week (from 0 to 6) for the 
> specified date.
> Note: Sunday is 0, Monday is 1, and so on.
> And chronos the Day of week from 1 to 7, Sunday is 7
> Best regards
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/paragi/chronos/issues/2#issuecomment-156702484.

## 

Simon Rigét
Kløvermarksvej 17
Annisse
3200 Helsinge
Tlf. 4096 8217

**Comment by pascalStm** [comment]
Hi Simon

your code and my code with trace

//// test.js
var chronos=require('e-chron');
console.log(chronos.nextTime("\* \* w1,7 1 0",false,1447400000));

chronos.add("\* \* w1,2,3,4,5,6,7 \* \* /5", function(){
    console.log("chronos");});
////

pascal@pascal-desktop:~/git/chronos$ date 11150918
dimanche 15 novembre 2015, 09:18:00 (UTC+0100)
pascal@pascal-desktop:~/git/chronos$ date
dimanche 15 novembre 2015, 09:18:02 (UTC+0100)
pascal@pascal-desktop:~/git/chronos$ nodejs ./test.js 
{ time: '1447545600.000', error: '' }
^C <-  no trace

pascal@pascal-desktop:~/git/chronos$ date
dimanche 15 novembre 2015, 09:18:44 (UTC+0100)
pascal@pascal-desktop:~/git/chronos$ date 11160918
timestamp too far in the future: Nov 16 09:18:42 2015
lundi 16 novembre 2015, 09:18:00 (UTC+0100)
pascal@pascal-desktop:~/git/chronos$ 
pascal@pascal-desktop:~/git/chronos$ nodejs ./test.js 
{ time: '1447545600.000', error: '' }
chronos   <- ok 
chronos
chronos
^C
pascal@pascal-desktop:~/git/chronos$ date
lundi 16 novembre 2015, 09:18:24 (UTC+0100)
pascal@pascal-desktop:~/git/chronos$ 

////

Best regards
Pascal

**Comment by paragi** [comment]
Bug fix: late Sunday bug 
Description
When using week day flag, with more then one day specified, on a Sunday, after the appointed execution time, execution is scheduled to next coming Sunday, ignoring other weekdays. 

Status Fixed in v 0.9.4

Hi Pacsal
Thank you for the useful example!
I have fixed the bug you have reported. 
Would you be kind enough to confirm that it solves your issue completely?

The bug is as you so keenly observed in line 523
I would however strongly suggest that you replace it with this line:
nt[10]=(((date.getDay()+6)%7)+1);
or install the new version from the repository.

Please let me know how it works.

Best regards
Simon Rigét

**Comment by pascalStm** [comment]
Hi Simon

my first tests are conclusive, Thank you!!!

Best regards
Pascal
